name: xchaindart
description: Lightweight dart library for cross-chain wallets.
version: 0.0.1
homepage: https://github.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  # TODO: remove flutter in the future.
  flutter: ">=1.17.0"

dependencies:
  #flutter:
  #  sdk: flutter

  bip39: ^1.0.3

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  test: ^1.17.4