name: xchaindart
description: Lightweight dart library for cross-chain wallets.
version: 0.0.6
homepage: https://github.com/DragonsDex/xchaindart

environment:
  sdk: ">=2.12.0 <3.0.0"
  # TODO: remove flutter in the future.
  flutter: ">=1.17.0"

dependencies:
  #flutter:
  #  sdk: flutter

  bip39: ^1.0.3
  http: ^0.13.3
  pointycastle: ^3.1.2
  uuid: ^3.0.1
  bitcoin_flutter:
    path: ../bitcoin_flutter

dependency_overrides:
  bip32:
    git:
      url: git://github.com/cochainio/bip32-dart
      ref: master
  bip39:
    git:
      url: git://github.com/cochainio/bip39
      ref: master
  pointycastle:
    git:
      url: git://github.com/cochainio/pc-dart
      ref: master

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  test: ^1.17.10

